{% set name = "qe" %}
{% set version = "6.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QEF/q-e/archive/{{ name }}-{{ version }}.tar.gz
  sha256: 11364f931894555f296f176ca91757f9a8d510f8e5264ced60e82e11c6de725f

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - openmpi-mpifort
    - make
  host:
    - fftw
    - fox
    - libblas
    - libcblas
    - libgomp
    - liblapack
    - liblapacke
    - openmpi
    - scalapack
  run:
    - fftw
    - openmpi
    - scalapack

test:
  commands:
    - test -f ${PREFIX}/bin/alpha2f.x
    - test -f ${PREFIX}/bin/average.x
    - test -f ${PREFIX}/bin/bands.x
    - test -f ${PREFIX}/bin/cell2ibrav.x
    - test -f ${PREFIX}/bin/cppp.x
    - test -f ${PREFIX}/bin/cp.x
    - test -f ${PREFIX}/bin/dos.x
    - test -f ${PREFIX}/bin/dvscf_q2r.x
    - test -f ${PREFIX}/bin/dynmat.x
    - test -f ${PREFIX}/bin/epa.x
    - test -f ${PREFIX}/bin/epsilon.x
    - test -f ${PREFIX}/bin/ev.x
    - test -f ${PREFIX}/bin/fermi_proj.x
    - test -f ${PREFIX}/bin/fermi_velocity.x
    - test -f ${PREFIX}/bin/fqha.x
    - test -f ${PREFIX}/bin/fs.x
    - test -f ${PREFIX}/bin/ibrav2cell.x
    - test -f ${PREFIX}/bin/initial_state.x
    - test -f ${PREFIX}/bin/iotk_print_kinds.x
    - test -f ${PREFIX}/bin/iotk.x
    - test -f ${PREFIX}/bin/kpoints.x
    - test -f ${PREFIX}/bin/lambda.x
    - test -f ${PREFIX}/bin/ld1.x
    - test -f ${PREFIX}/bin/manycp.x
    - test -f ${PREFIX}/bin/matdyn.x
    - test -f ${PREFIX}/bin/molecularpdos.x
    - test -f ${PREFIX}/bin/neb.x
    - test -f ${PREFIX}/bin/open_grid.x
    - test -f ${PREFIX}/bin/path_interpolation.x
    - test -f ${PREFIX}/bin/pawplot.x
    - test -f ${PREFIX}/bin/phcg.x
    - test -f ${PREFIX}/bin/ph.x
    - test -f ${PREFIX}/bin/plan_avg.x
    - test -f ${PREFIX}/bin/plotband.x
    - test -f ${PREFIX}/bin/plotproj.x
    - test -f ${PREFIX}/bin/plotrho.x
    - test -f ${PREFIX}/bin/pmw.x
    - test -f ${PREFIX}/bin/postahc.x
    - test -f ${PREFIX}/bin/ppacf.x
    - test -f ${PREFIX}/bin/pp.x
    - test -f ${PREFIX}/bin/projwfc.x
    - test -f ${PREFIX}/bin/pw2bgw.x
    - test -f ${PREFIX}/bin/pw2critic.x
    - test -f ${PREFIX}/bin/pw2gw.x
    - test -f ${PREFIX}/bin/pw2wannier90.x
    - test -f ${PREFIX}/bin/pwcond.x
    - test -f ${PREFIX}/bin/pwi2xsf.x
    - test -f ${PREFIX}/bin/pw.x
    - test -f ${PREFIX}/bin/q2qstar.x
    - test -f ${PREFIX}/bin/q2r.x
    - test -f ${PREFIX}/bin/scan_ibrav.x
    - test -f ${PREFIX}/bin/sumpdos.x
    - test -f ${PREFIX}/bin/upfconv.x
    - test -f ${PREFIX}/bin/virtual_v2.x
    - test -f ${PREFIX}/bin/wannier_ham.x
    - test -f ${PREFIX}/bin/wannier_plot.x
    - test -f ${PREFIX}/bin/wfck2r.x
    - test -f ${PREFIX}/bin/wfdd.x
    - test -f ${PREFIX}/bin/xctest_qe_libxc.x

about:
  home: http://www.quantum-espresso.org
  license: GPL-2.0-only
  license_family: GPL
  license_file: License
  summary: QUANTUM ESPRESSO (opEn-Source Package for Research in Electronic Structure, Simulation, and Optimization)

  description: |
    QUANTUM ESPRESSO is an integrated suite of Open-Source computer 
    codes for electronic-structure calculations and materials modeling 
    at the nanoscale. It is based on density-functional theory, plane 
    waves, and pseudopotentials.
  doc_url: http://www.quantum-espresso.org/Doc/user_guide/
  dev_url: https://github.com/QEF/q-e

extra:
  recipe-maintainers:
    - jan-janssen
    - certik
    - wolfv
