conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
provider:
  linux_aarch64: azure
conda_install_tool: pixi
conda_build_tool: rattler-build
